# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "hlahd"
description: HLA-HD is a tool for HLA typing from NGS data
keywords:
  - hla
  - typing
  - genomics
  - ngs
tools:
  - "hlahd":
      description: "HLA-HD: HLA typing from High-quality Dictionary"
      homepage: "https://w3.genome.med.kyoto-u.ac.jp/HLA-HD/"
      documentation: "https://w3.genome.med.kyoto-u.ac.jp/HLA-HD/"
      tool_dev_url: "https://w3.genome.med.kyoto-u.ac.jp/HLA-HD/"
      doi: "doi: 10.1002/humu.23230"
      licence: ["Proprietary"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - reads:
        type: file
        description: List of input FastQ files of size 1 and 2 for single-end and paired-end data, respectively.
        pattern: "*.{fastq.gz,fq.gz}"

output:
  - result:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*_final.result.txt":
          type: file
          description: Final HLA typing result file
          pattern: "*_final.result.txt"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@riederd"
maintainers:
  - "@riederd"
